version: 2.0
output_directory: /live_response/packages
artifacts:
  -
    description: Display all applications located at /Applications directory.
    supported_os: [macos]
    collector: command
    command: ls -l -a /%mount_point%/Applications
    output_file: ls_-l_-a_Applications.txt
  -
    description: Display all applications located at /Users/%user%/Applications directory.
    supported_os: [macos]
    collector: command
    command: ls -l -a /%user_home%/Applications
    output_file: ls_-l_-a_%user_home%_Applications.txt
    exclude_nologin_users: true
