version: 2.0
condition: command_exists "service"
output_directory: /live_response/system
artifacts:
  -
    description: Display System V services status information.
    supported_os: [linux]
    collector: command
    command: service --status-all
    output_file: service_--status-all.txt
  